use_frameworks!

def build_pods
    pod 'EasterDate', :path => '../'
end

def test_pods
    pod 'Quick', '~> 0.8'
    pod 'Nimble', '~> 3.0'
end

target 'EasterDate Example iOS' do
    build_pods

    target 'EasterDate Tests iOS' do
        test_pods
    end
end

target 'EasterDate Example Mac' do
    build_pods

    target 'EasterDate Tests Mac' do
        test_pods
    end
end
