use_frameworks!

def build_pods
    pod 'EasterDate', :path => '../'
end

def test_pods
end

target 'EasterDate Example iOS' do
    build_pods

    target 'EasterDate Tests iOS' do
        test_pods
    end
end

target 'EasterDate Example Mac' do
    build_pods

    target 'EasterDate Tests Mac' do
        test_pods
    end
end

target 'EasterDate Example tvOS' do
    build_pods

    target 'EasterDate Tests tvOS' do
        test_pods
    end
end
