use_frameworks!

def testing_pods
    pod 'Quick', '~> 0.8'
    pod 'Nimble', '~> 3.0'
end

def target_pods
    pod 'EasterDate', :path => '../'
end

target 'EasterDate_Example' do
    target_pods

    target 'EasterDate_Tests' do
        inherit! :search_paths
        target_pods
        testing_pods
    end
end
